import type { CanonicalTestCase, CanonicalTestStep, PersistedSuite } from "@sonofcotester/sdk";

export function exportTestCaseToPlaywright(testCase: CanonicalTestCase, baseUrl = "http://localhost:3010"): string {
  const lines: string[] = [];
  lines.push(`  test("${testCase.title.replace(/"/g, '\\"')}", async ({ page }) => {`);

  for (const step of testCase.steps) {
    lines.push(`    // ${step.expectedOutcome || `${step.action} ${step.target || ""}`.trim()}`);
    switch (step.action) {
      case "navigate": {
        const dest = step.data || baseUrl || "/";
        lines.push(`    await page.goto("${dest.replace(/"/g, '\\"')}", { waitUntil: "domcontentloaded" });`);
        break;
      }
      case "click": {
        if (step.target) {
          lines.push(`    await page.locator("${step.target.replace(/"/g, '\\"')}").first().click();`);
        }
        break;
      }
      case "fill": {
        if (step.target) {
          lines.push(`    await page.locator("${step.target.replace(/"/g, '\\"')}").first().fill("${(step.data || "").replace(/"/g, '\\"')}");`);
        }
        break;
      }
      case "assertVisible": {
        if (step.target) {
          lines.push(`    await expect(page.locator("${step.target.replace(/"/g, '\\"')}").first()).toBeVisible();`);
        }
        break;
      }
      case "assertText": {
        if (step.target) {
          lines.push(`    await expect(page.locator("${step.target.replace(/"/g, '\\"')}").first()).toContainText("${(step.data || "").replace(/"/g, '\\"')}");`);
        }
        break;
      }
      default:
        break;
    }
  }

  lines.push(`  });`);
  return lines.join("\n");
}

export function exportSuiteToPlaywright(suite: PersistedSuite, baseUrl = "http://localhost:3010"): string {
  const cases = suite.versions[0]?.cases || [];
  const testBlocks = cases.map((c) => exportTestCaseToPlaywright(c, baseUrl)).join("\n\n");

  return `import { test, expect } from "@playwright/test";

/**
 * Suite: ${suite.summary}
 * Generated by Son of CodeTester Autonomous QA Engine
 * Target: ${baseUrl}
 */
test.describe("${suite.summary.replace(/"/g, '\\"')}", () => {
  test.beforeEach(async ({ page }) => {
    // Optional viewport setup
    await page.setViewportSize({ width: 1280, height: 800 });
  });

${testBlocks}
});
`;
}

export function exportSuiteToMaestroYaml(suite: PersistedSuite, appId = "com.example.app"): string {
  const cases = suite.versions[0]?.cases || [];
  const flows: string[] = [];

  for (const testCase of cases) {
    const lines: string[] = [];
    lines.push(`appId: ${appId}`);
    lines.push(`name: "${testCase.title.replace(/"/g, '\\"')}"`);
    lines.push(`---`);
    lines.push(`- launchApp`);

    for (const step of testCase.steps) {
      switch (step.action) {
        case "navigate":
          if (step.data && step.data.startsWith("http")) {
            lines.push(`- openLink: "${step.data}"`);
          }
          break;
        case "click":
          if (step.target) {
            lines.push(`- tapOn: "${step.target.replace(/"/g, '\\"')}"`);
          }
          break;
        case "fill":
          if (step.target) {
            lines.push(`- tapOn: "${step.target.replace(/"/g, '\\"')}"`);
            lines.push(`- inputText: "${(step.data || "").replace(/"/g, '\\"')}"`);
          }
          break;
        case "assertVisible":
          if (step.target) {
            lines.push(`- assertVisible: "${step.target.replace(/"/g, '\\"')}"`);
          }
          break;
        case "assertText":
          if (step.data) {
            lines.push(`- assertVisible: "${step.data.replace(/"/g, '\\"')}"`);
          }
          break;
        default:
          break;
      }
    }
    flows.push(lines.join("\n"));
  }

  return flows.join("\n\n---\n\n");
}

export function exportGitHubActionsWorkflow(suiteName = "e2e-tests"): string {
  return `name: Son of CodeTester E2E Continuous Verification

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Run Autonomous E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run E2E Test Suite
        run: pnpm exec playwright test
        env:
          CI: true
          TARGET_URL: http://localhost:3000

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
`;
}
